export const FETCH_CONSTRAINTS_REQUEST = 'FETCH_CONSTRAINTS_REQUEST';
export const FETCH_CONSTRAINTS_SUCCESS = 'FETCH_CONSTRAINTS_SUCCESS';
export const FETCH_CONSTRAINTS_FAILURE = 'FETCH_CONSTRAINTS_FAILURE';
