export const CREATE_JOINT_TEACHING_GROUP =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP';
export const CREATE_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_REQUEST';
export const CREATE_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_SUCCESS';
export const CREATE_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_FAILURE';

export const DELETE_JOINT_TEACHING_GROUP =
  '@@jointTeaching/DELETE_JOINT_TEACHING_GROUP';
export const DELETE_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/DELETE_JOINT_TEACHING_GROUP_REQUEST';
export const DELETE_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/DELETE_JOINT_TEACHING_GROUP_SUCCESS';
export const DELETE_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/DELETE_JOINT_TEACHING_GROUP_FAILURE';

export const FETCH_JOINT_TEACHING_GROUPS_FOR_FORM =
  '@@jointTeaching/FETCH_JOINT_TEACHING_GROUPS_FOR_FORM';
export const FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_REQUEST =
  '@@jointTeaching/FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_REQUEST';
export const FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_SUCCESS =
  '@@jointTeaching/FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_SUCCESS';
export const FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_FAILURE =
  '@@jointTeaching/FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_FAILURE';

export const DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP =
  '@@jointTeaching/DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP';
export const DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_REQUEST';
export const DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_SUCCESS';
export const DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_FAILURE';

export const ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP =
  '@@jointTeaching/ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP';
export const ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_REQUEST';
export const ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_SUCCESS';
export const ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_FAILURE';
