export const CREATE_JOINT_TEACHING_GROUP =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP';
export const CREATE_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_REQUEST';
export const CREATE_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_SUCCESS';
export const CREATE_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_FAILURE';
