export const CREATE_JOINT_TEACHING_GROUP =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP';
export const CREATE_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_REQUEST';
export const CREATE_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_SUCCESS';
export const CREATE_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/CREATE_JOINT_TEACHING_GROUP_FAILURE';

export const CREATE_THEN_MERGE_JOINT_TEACHING_GROUP =
  '@@jointTeaching/CREATE_THEN_MERGE_JOINT_TEACHING_GROUP';
export const CREATE_THEN_MERGE_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/CREATE_THEN_MERGE_JOINT_TEACHING_GROUP_REQUEST';
export const CREATE_THEN_MERGE_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/CREATE_THEN_MERGE_JOINT_TEACHING_GROUP_SUCCESS';
export const CREATE_THEN_MERGE_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/CREATE_THEN_MERGE_JOINT_TEACHING_GROUP_FAILURE';

export const DELETE_JOINT_TEACHING_GROUP =
  '@@jointTeaching/DELETE_JOINT_TEACHING_GROUP';
export const DELETE_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/DELETE_JOINT_TEACHING_GROUP_REQUEST';
export const DELETE_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/DELETE_JOINT_TEACHING_GROUP_SUCCESS';
export const DELETE_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/DELETE_JOINT_TEACHING_GROUP_FAILURE';

export const FETCH_JOINT_TEACHING_GROUPS_FOR_FORM =
  '@@jointTeaching/FETCH_JOINT_TEACHING_GROUPS_FOR_FORM';
export const FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_REQUEST =
  '@@jointTeaching/FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_REQUEST';
export const FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_SUCCESS =
  '@@jointTeaching/FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_SUCCESS';
export const FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_FAILURE =
  '@@jointTeaching/FETCH_JOINT_TEACHING_GROUPS_FOR_FORM_FAILURE';

export const DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP =
  '@@jointTeaching/DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP';
export const DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_REQUEST';
export const DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_SUCCESS';
export const DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/DELETE_ACTIVITY_FROM_JOINT_TEACHING_GROUP_FAILURE';

export const ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP =
  '@@jointTeaching/ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP';
export const ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_REQUEST';
export const ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_SUCCESS';
export const ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/ADD_ACTIVITY_TO_JOINT_TEACHING_GROUP_FAILURE';

export const GENERATE_JOINT_TEACHING_GROUP =
  '@@jointTeaching/GENERATE_JOINT_TEACHING_GROUP';
export const GENERATE_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/GENERATE_JOINT_TEACHING_GROUP_REQUEST';
export const GENERATE_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/GENERATE_JOINT_TEACHING_GROUP_SUCCESS';
export const GENERATE_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/GENERATE_JOINT_TEACHING_GROUP_FAILURE';

export const MERGE_JOINT_TEACHING_GROUP =
  '@@jointTeaching/MERGE_JOINT_TEACHING_GROUP';
export const MERGE_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/MERGE_JOINT_TEACHING_GROUP_REQUEST';
export const MERGE_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/MERGE_JOINT_TEACHING_GROUP_SUCCESS';
export const MERGE_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/MERGE_JOINT_TEACHING_GROUP_FAILURE';

export const REVERT_JOINT_TEACHING_GROUP =
  '@@jointTeaching/REVERT_JOINT_TEACHING_GROUP';
export const REVERT_JOINT_TEACHING_GROUP_REQUEST =
  '@@jointTeaching/REVERT_JOINT_TEACHING_GROUP_REQUEST';
export const REVERT_JOINT_TEACHING_GROUP_SUCCESS =
  '@@jointTeaching/REVERT_JOINT_TEACHING_GROUP_SUCCESS';
export const REVERT_JOINT_TEACHING_GROUP_FAILURE =
  '@@jointTeaching/REVERT_JOINT_TEACHING_GROUP_FAILURE';

export const ADD_JOINT_TEACHING_CONFLICT =
  '@@jointTeaching/ADD_JOINT_TEACHING_CONFLICT';
export const ADD_JOINT_TEACHING_CONFLICT_REQUEST =
  '@@jointTeaching/ADD_JOINT_TEACHING_CONFLICT_REQUEST';
export const ADD_JOINT_TEACHING_CONFLICT_SUCCESS =
  '@@jointTeaching/ADD_JOINT_TEACHING_CONFLICT_SUCCESS';
export const ADD_JOINT_TEACHING_CONFLICT_FAILURE =
  '@@jointTeaching/ADD_JOINT_TEACHING_CONFLICT_FAILURE ';

export const UPDATE_JOINT_TEACHING_CONFLICT =
  '@@jointTeaching/UPDATE_JOINT_TEACHING_CONFLICT';
export const UPDATE_JOINT_TEACHING_CONFLICT_REQUEST =
  '@@jointTeaching/UPDATE_JOINT_TEACHING_CONFLICT_REQUEST';
export const UPDATE_JOINT_TEACHING_CONFLICT_SUCCESS =
  '@@jointTeaching/UPDATE_JOINT_TEACHING_CONFLICT_SUCCESS';
export const UPDATE_JOINT_TEACHING_CONFLICT_FAILURE =
  '@@jointTeaching/UPDATE_JOINT_TEACHING_CONFLICT_FAILURE ';

export const REMOVE_JOINT_TEACHING_CONFLICT =
  '@@jointTeaching/REMOVE_JOINT_TEACHING_CONFLICT';
export const REMOVE_JOINT_TEACHING_CONFLICT_REQUEST =
  '@@jointTeaching/REMOVE_JOINT_TEACHING_CONFLICT_REQUEST';
export const REMOVE_JOINT_TEACHING_CONFLICT_SUCCESS =
  '@@jointTeaching/REMOVE_JOINT_TEACHING_CONFLICT_SUCCESS';
export const REMOVE_JOINT_TEACHING_CONFLICT_FAILURE =
  '@@jointTeaching/REMOVE_JOINT_TEACHING_CONFLICT_FAILURE';

export const CALCULATE_JOINT_TEACHING_MATCHING_SCORE =
  '@@jointTeaching/CALCULATE_JOINT_TEACHING_MATCHING_SCORE';
export const CALCULATE_JOINT_TEACHING_MATCHING_SCORE_REQUEST =
  '@@jointTeaching/CALCULATE_JOINT_TEACHING_MATCHING_SCORE_REQUEST';
export const CALCULATE_JOINT_TEACHING_MATCHING_SCORE_SUCCESS =
  '@@jointTeaching/CALCULATE_JOINT_TEACHING_MATCHING_SCORE_SUCCESS';
export const CALCULATE_JOINT_TEACHING_MATCHING_SCORE_FAILURE =
  '@@jointTeaching/CALCULATE_JOINT_TEACHING_MATCHING_SCORE_FAILURE';
