export const FETCH_RECIPIENTS = 'FETCH_RECIPIENTS';
export const FETCH_RECIPIENTS_REQUEST = 'FETCH_RECIPIENTS_REQUEST';
export const FETCH_RECIPIENTS_SUCCESS = 'FETCH_RECIPIENTS_SUCCESS';
export const FETCH_RECIPIENTS_FAILURE = 'FETCH_RECIPIENTS_FAILURE';
