export const dummyActivityDesign = {
  name: 'Mapping for 60e7fb35d3241f0026cd5a04',
  formId: '60e7fb35d3241f0026cd5a04',
  timing: {
    mode: 'EXACT',
    startDate: [],
    endDate: [],
    startTime: ['60e7fb62d3241f0026cd5a47', 'startTime'],
    endTime: ['60e7fb62d3241f0026cd5a47', 'endTime'],
    length: [],
    padding: [],
    dateRanges: [],
    weekday: [],
    time: [],
  },
  objects: {
    accinfo: [['scopedObject']],
    availgrp_room: [['60e7fb62d3241f0026cd5a47', '60e7fb62d3241f0026cd5a45']],
    activity: [['60e7fb62d3241f0026cd5a47', '60e7fb62d3241f0026cd5a46']],
  },
  fields: {},
  propSettings: {
    accinfo: {
      mandatory: true,
    },
    activity: {
      mandatory: true,
    },
    availgrp_room: {
      mandatory: true,
    },
  },
  isEditable: false,
};
export const dummyActivities = [
  {
    _id: '60ed0c2179e86d0023bda35e',
    formId: '60e7fb35d3241f0026cd5a04',
    formInstanceId: '60e7fb62d3241f0026cd5a61',
    tagId: null,
    sectionId: '60e7fb62d3241f0026cd5a47',
    eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
    rowIdx: null,
    activityStatus: 'NOT_SCHEDULED',
    errorDetails: {},
    schedulingTimestamp: null,
    timing: [
      {
        type: 'timing',
        extId: '$init',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'mode',
        value: 'EXACT',
        submissionValue: ['EXACT'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startTime',
        value: '2021-07-10T04:00:00Z',
        submissionValue: ['2021-07-10T04:00:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endTime',
        value: '2021-07-10T05:00:00Z',
        submissionValue: ['2021-07-10T05:00:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'length',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'padding',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'weekday',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'time',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
    ],
    values: [
      {
        type: 'object',
        extId: 'accinfo',
        value: ['_te_2473'],
        submissionValue: ['_te_2473'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: 'scopedObject',
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'availgrp_room',
        value: [1],
        submissionValue: [1],
        submissionValueType: 'FREE_TEXT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a45',
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'activity',
        value: ['_te_81'],
        submissionValue: ['_te_81'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a46',
        eventId: '44f330eb-56a4-4598-b4cb-7fe129794514',
        rowIdx: null,
      },
    ],
    sequenceIdx: 0,
    organizationId: '5c3e8d130000000000000001',
  },
  {
    _id: '60ed0c2179e86d0023bda360',
    formId: '60e7fb35d3241f0026cd5a04',
    formInstanceId: '60e7fb62d3241f0026cd5a61',
    tagId: null,
    sectionId: '60e7fb62d3241f0026cd5a47',
    eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
    rowIdx: null,
    activityStatus: 'NOT_SCHEDULED',
    errorDetails: {},
    schedulingTimestamp: null,
    timing: [
      {
        type: 'timing',
        extId: '$init',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'mode',
        value: 'EXACT',
        submissionValue: ['EXACT'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startTime',
        value: '2021-07-11T03:45:00Z',
        submissionValue: ['2021-07-11T03:45:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endTime',
        value: '2021-07-11T04:15:00Z',
        submissionValue: ['2021-07-11T04:15:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'length',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'padding',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'weekday',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'time',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
    ],
    values: [
      {
        type: 'object',
        extId: 'accinfo',
        value: ['_te_2473'],
        submissionValue: ['_te_2473'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: 'scopedObject',
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'availgrp_room',
        value: [2],
        submissionValue: [2],
        submissionValueType: 'FREE_TEXT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a45',
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'activity',
        value: ['_te_2489'],
        submissionValue: ['_te_2489'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a46',
        eventId: '86fd4a00-4b56-4c39-8684-3464c7f14cb1',
        rowIdx: null,
      },
    ],
    sequenceIdx: 1,
    organizationId: '5c3e8d130000000000000001',
  },
  {
    _id: '60ed0c2179e86d0023bda362',
    formId: '60e7fb35d3241f0026cd5a04',
    formInstanceId: '60e7fb62d3241f0026cd5a61',
    tagId: null,
    sectionId: '60e7fb62d3241f0026cd5a47',
    eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
    rowIdx: null,
    activityStatus: 'NOT_SCHEDULED',
    errorDetails: {},
    schedulingTimestamp: null,
    timing: [
      {
        type: 'timing',
        extId: '$init',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'mode',
        value: 'EXACT',
        submissionValue: ['EXACT'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startTime',
        value: '2021-07-11T02:45:00Z',
        submissionValue: ['2021-07-11T02:45:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endTime',
        value: '2021-07-11T03:00:00Z',
        submissionValue: ['2021-07-11T03:00:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'length',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'padding',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'weekday',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'time',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
    ],
    values: [
      {
        type: 'object',
        extId: 'accinfo',
        value: ['_te_2473'],
        submissionValue: ['_te_2473'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: 'scopedObject',
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'availgrp_room',
        value: [null],
        submissionValue: [null],
        submissionValueType: 'FREE_TEXT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a45',
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'activity',
        value: ['_te_2491'],
        submissionValue: ['_te_2491'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a46',
        eventId: 'c4ea36e7-5214-42b2-8299-b0ee3ca0196a',
        rowIdx: null,
      },
    ],
    sequenceIdx: 2,
    organizationId: '5c3e8d130000000000000001',
  },
  {
    _id: '60ed0c2179e86d0023bda364',
    formId: '60e7fb35d3241f0026cd5a04',
    formInstanceId: '60e7fb62d3241f0026cd5a61',
    tagId: null,
    sectionId: '60e7fb62d3241f0026cd5a47',
    eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
    rowIdx: null,
    activityStatus: 'NOT_SCHEDULED',
    errorDetails: {},
    schedulingTimestamp: null,
    timing: [
      {
        type: 'timing',
        extId: '$init',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'mode',
        value: 'EXACT',
        submissionValue: ['EXACT'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startTime',
        value: '2021-07-10T02:00:00Z',
        submissionValue: ['2021-07-10T02:00:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endTime',
        value: '2021-07-10T03:00:00Z',
        submissionValue: ['2021-07-10T03:00:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'length',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'padding',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'weekday',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'time',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
    ],
    values: [
      {
        type: 'object',
        extId: 'accinfo',
        value: ['_te_2473'],
        submissionValue: ['_te_2473'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: 'scopedObject',
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'availgrp_room',
        value: [4],
        submissionValue: [4],
        submissionValueType: 'FREE_TEXT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a45',
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'activity',
        value: ['_te_2488'],
        submissionValue: ['_te_2488'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a46',
        eventId: 'e85a0aef-f281-4dca-b124-593f47d4e3ed',
        rowIdx: null,
      },
    ],
    sequenceIdx: 3,
    organizationId: '5c3e8d130000000000000001',
  },
  {
    _id: '60ed0c2179e86d0023bda366',
    formId: '60e7fb35d3241f0026cd5a04',
    formInstanceId: '60e7fb62d3241f0026cd5a61',
    tagId: null,
    sectionId: '60e7fb62d3241f0026cd5a47',
    eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
    rowIdx: null,
    activityStatus: 'NOT_SCHEDULED',
    errorDetails: {},
    schedulingTimestamp: null,
    timing: [
      {
        type: 'timing',
        extId: '$init',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'mode',
        value: 'EXACT',
        submissionValue: ['EXACT'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startTime',
        value: '2021-07-11T01:30:00Z',
        submissionValue: ['2021-07-11T01:30:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endTime',
        value: '2021-07-11T02:45:00Z',
        submissionValue: ['2021-07-11T02:45:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'length',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'padding',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'weekday',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'time',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
    ],
    values: [
      {
        type: 'object',
        extId: 'accinfo',
        value: ['_te_2473'],
        submissionValue: ['_te_2473'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: 'scopedObject',
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'availgrp_room',
        value: [null],
        submissionValue: [null],
        submissionValueType: 'FREE_TEXT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a45',
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'activity',
        value: [null],
        submissionValue: [null],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a46',
        eventId: 'db890bd6-7d0f-4cf8-b8de-2cda2f39bbd6',
        rowIdx: null,
      },
    ],
    sequenceIdx: 4,
    organizationId: '5c3e8d130000000000000001',
  },
  {
    _id: '60ed0c2179e86d0023bda368',
    formId: '60e7fb35d3241f0026cd5a04',
    formInstanceId: '60e7fb62d3241f0026cd5a61',
    tagId: null,
    sectionId: '60e7fb62d3241f0026cd5a47',
    eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
    rowIdx: null,
    activityStatus: 'NOT_SCHEDULED',
    errorDetails: {},
    schedulingTimestamp: null,
    timing: [
      {
        type: 'timing',
        extId: '$init',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'mode',
        value: 'EXACT',
        submissionValue: ['EXACT'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startTime',
        value: '2021-07-11T03:15:00Z',
        submissionValue: ['2021-07-11T03:15:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endTime',
        value: '2021-07-11T03:30:00Z',
        submissionValue: ['2021-07-11T03:30:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'length',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'padding',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'weekday',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'time',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
    ],
    values: [
      {
        type: 'object',
        extId: 'accinfo',
        value: ['_te_2473'],
        submissionValue: ['_te_2473'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: 'scopedObject',
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'availgrp_room',
        value: [null],
        submissionValue: [null],
        submissionValueType: 'FREE_TEXT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a45',
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'activity',
        value: ['_te_2489'],
        submissionValue: ['_te_2489'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a46',
        eventId: 'f7235c2a-679b-43b0-a716-1fbe637924e1',
        rowIdx: null,
      },
    ],
    sequenceIdx: 5,
    organizationId: '5c3e8d130000000000000001',
  },
  {
    _id: '60ed0c2279e86d0023bda369',
    formId: '60e7fb35d3241f0026cd5a04',
    formInstanceId: '60e7fb62d3241f0026cd5a61',
    tagId: null,
    sectionId: '60e7fb62d3241f0026cd5a47',
    eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
    rowIdx: null,
    activityStatus: 'NOT_SCHEDULED',
    errorDetails: {},
    schedulingTimestamp: null,
    timing: [
      {
        type: 'timing',
        extId: '$init',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'mode',
        value: 'EXACT',
        submissionValue: ['EXACT'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endDate',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'startTime',
        value: '2021-07-11T04:45:00Z',
        submissionValue: ['2021-07-11T04:45:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'endTime',
        value: '2021-07-11T05:45:00Z',
        submissionValue: ['2021-07-11T05:45:00Z'],
        submissionValueType: 'TIMING',
        valueMode: 'FROM_SUBMISSION',
        sectionId: null,
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'length',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'padding',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'weekday',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
      {
        type: 'timing',
        extId: 'time',
        value: null,
        submissionValue: null,
        submissionValueType: null,
        valueMode: null,
        sectionId: null,
        elementId: null,
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
    ],
    values: [
      {
        type: 'object',
        extId: 'accinfo',
        value: ['_te_2473'],
        submissionValue: ['_te_2473'],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: 'scopedObject',
        elementId: null,
        eventId: null,
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'availgrp_room',
        value: [null],
        submissionValue: [null],
        submissionValueType: 'FREE_TEXT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a45',
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
      {
        type: 'object',
        extId: 'activity',
        value: [null],
        submissionValue: [null],
        submissionValueType: 'OBJECT',
        valueMode: 'FROM_SUBMISSION',
        sectionId: '60e7fb62d3241f0026cd5a47',
        elementId: '60e7fb62d3241f0026cd5a46',
        eventId: 'a57b072a-b455-4dc0-932f-f2d55443142f',
        rowIdx: null,
      },
    ],
    sequenceIdx: 6,
    organizationId: '5c3e8d130000000000000001',
  },
];
