export const START_SCHEDULING_ACTIVITIES =
  '@@activityScheduling/START_SCHEDULING_ACTIVITIES';
export const FINISH_SCHEDULING_ACTIVITIES =
  '@@activityScheduling/FINISH_SCHEDULING_ACTIVITIES';

export const SCHEDULING_ACTIVITY_REQUEST =
  '@@activityScheduling/SCHEDULING_ACTIVITY_REQUEST';
export const SCHEDULING_ACTIVITY_SUCCESS =
  '@@activityScheduling/SCHEDULING_ACTIVITY_SUCCESS';
export const SCHEDULING_ACTIVITY_FAILED =
  '@@activityScheduling/SCHEDULING_ACTIVITY_FAILED';

export const SCHEDULING_ACTIVITY_FORM_INSTANCE_ID_REQUEST =
  '@@activityScheduling/SCHEDULING_ACTIVITY_FORM_INSTANCE_ID_REQUEST';
export const SCHEDULING_ACTIVITY_FORM_INSTANCE_ID_SUCCESS =
  '@@activityScheduling/SCHEDULING_ACTIVITY_FORM_INSTANCE_ID_SUCCESS';
export const SCHEDULING_ACTIVITY_FORM_INSTANCE_ID_FAILED =
  '@@activityScheduling/SCHEDULING_ACTIVITY_FORM_INSTANCE_ID_FAILED';
