import { screen } from '@testing-library/react';
import type { TActivity } from 'Types/Activity.type';
import JointTeachingGroupMerger from '../JointTeachingGroupMerger';
import { renderWithState } from '../../../Utils/test.utils';

describe('Joint Teaching Group tests', () => {
  const activities = {
    '601048c0ea0edb00206dae89': [
      {
        _id: '6093a60ecdb17300258c7ae4',
        formId: '60104814ea0edb00206dadfe',
        formInstanceId: '601048c0ea0edb00206dae89',
        tagId: null,
        sectionId: '601048afea0edb00206dae62',
        eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
        rowIdx: null,
        activityStatus: 'NOT_SCHEDULED',
        errorDetails: {},
        schedulingTimestamp: null,
        timing: [
          {
            type: 'timing',
            extId: '$init',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'mode',
            value: 'EXACT',
            submissionValue: ['EXACT'],
            submissionValueType: 'TIMING',
            valueMode: 'FROM_SUBMISSION',
            sectionId: null,
            elementId: null,
            eventId: null,
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'startDate',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'endDate',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'startTime',
            value: '2021-02-02T08:00:00Z',
            submissionValue: ['2021-02-02T08:00:00Z'],
            submissionValueType: 'TIMING',
            valueMode: 'FROM_SUBMISSION',
            sectionId: null,
            elementId: null,
            eventId: null,
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'endTime',
            value: '2021-02-02T10:15:00Z',
            submissionValue: ['2021-02-02T10:15:00Z'],
            submissionValueType: 'TIMING',
            valueMode: 'FROM_SUBMISSION',
            sectionId: null,
            elementId: null,
            eventId: null,
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'length',
            value: null,
            submissionValue: {
              categories: [
                {
                  id: 'room.type',
                  values: ['Datorsal'],
                },
              ],
              searchString: null,
              searchFields: null,
            },
            submissionValueType: 'FILTER',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae69',
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'padding',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'weekday',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'time',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
        ],
        values: [
          {
            type: 'object',
            extId: 'room',
            value: {
              categories: [
                {
                  id: 'room.type',
                  values: ['Datorsal'],
                },
              ],
              searchString: null,
              searchFields: null,
            },
            submissionValue: {
              categories: [
                {
                  id: 'room.type',
                  values: ['Datorsal'],
                },
              ],
              searchString: null,
              searchFields: null,
            },
            submissionValueType: 'FILTER',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae69',
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'object',
            extId: 'person_staff',
            value: ['person_atsi0001'],
            submissionValue: ['person_atsi0001'],
            submissionValueType: 'OBJECT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae67',
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'object',
            extId: 'courseevt',
            value: ['courseevt_BI1143-40049-VT2021'],
            submissionValue: ['courseevt_BI1143-40049-VT2021'],
            submissionValueType: 'OBJECT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: 'scopedObject',
            elementId: null,
            eventId: null,
            rowIdx: null,
          },
          {
            type: 'object',
            extId: 'equipment',
            value: [],
            submissionValue: [],
            submissionValueType: 'OBJECT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae6d',
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'object',
            extId: 'activity_teach',
            value: ['course_activity_discussion'],
            submissionValue: ['course_activity_discussion'],
            submissionValueType: 'OBJECT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae6b',
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'field',
            extId: 'res.restext',
            value: 'Test',
            submissionValue: ['Test'],
            submissionValueType: 'FREE_TEXT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae63',
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
          {
            type: 'field',
            extId: 'res.comment',
            value: 'Testar lite bara på beta',
            submissionValue: ['Testar lite bara på beta'],
            submissionValueType: 'FREE_TEXT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae65',
            eventId: 'd308a62d-8874-43a6-b127-13ba31aa2f20',
            rowIdx: null,
          },
        ],
        sequenceIdx: 0,
      },
      {
        _id: '6093a60ecdb17300258c7ae5',
        formId: '60104814ea0edb00206dadfe',
        formInstanceId: '601048c0ea0edb00206dae89',
        tagId: null,
        sectionId: '601048afea0edb00206dae62',
        eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
        rowIdx: null,
        activityStatus: 'NOT_SCHEDULED',
        errorDetails: {},
        schedulingTimestamp: null,
        timing: [
          {
            type: 'timing',
            extId: '$init',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'mode',
            value: 'EXACT',
            submissionValue: ['EXACT'],
            submissionValueType: 'TIMING',
            valueMode: 'FROM_SUBMISSION',
            sectionId: null,
            elementId: null,
            eventId: null,
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'startDate',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'endDate',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'startTime',
            value: '2021-02-03T11:00:00Z',
            submissionValue: ['2021-02-03T11:00:00Z'],
            submissionValueType: 'TIMING',
            valueMode: 'FROM_SUBMISSION',
            sectionId: null,
            elementId: null,
            eventId: null,
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'endTime',
            value: '2021-02-03T14:00:00Z',
            submissionValue: ['2021-02-03T14:00:00Z'],
            submissionValueType: 'TIMING',
            valueMode: 'FROM_SUBMISSION',
            sectionId: null,
            elementId: null,
            eventId: null,
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'length',
            value: 120,
            submissionValue: {
              categories: [
                {
                  id: 'room.type',
                  values: ['Hörsal, gradäng'],
                },
              ],
              searchString: null,
              searchFields: null,
            },
            submissionValueType: 'FILTER',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae69',
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'padding',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'weekday',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'timing',
            extId: 'time',
            value: null,
            submissionValue: null,
            submissionValueType: null,
            valueMode: null,
            sectionId: null,
            elementId: null,
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
        ],
        values: [
          {
            type: 'object',
            extId: 'room',
            value: {
              categories: [
                {
                  id: 'room.type',
                  values: ['Hörsal, gradäng'],
                },
              ],
              searchString: null,
              searchFields: null,
            },
            submissionValue: {
              categories: [
                {
                  id: 'room.type',
                  values: ['Hörsal, gradäng'],
                },
              ],
              searchString: null,
              searchFields: null,
            },
            submissionValueType: 'FILTER',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae69',
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'object',
            extId: 'person_staff',
            value: ['person_auba0002'],
            submissionValue: ['person_auba0002'],
            submissionValueType: 'OBJECT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae67',
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'object',
            extId: 'courseevt',
            value: ['courseevt_BI1143-40049-VT2021'],
            submissionValue: ['courseevt_BI1143-40049-VT2021'],
            submissionValueType: 'OBJECT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: 'scopedObject',
            elementId: null,
            eventId: null,
            rowIdx: null,
          },
          {
            type: 'object',
            extId: 'equipment',
            value: [],
            submissionValue: [],
            submissionValueType: 'OBJECT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae6d',
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'object',
            extId: 'activity_teach',
            value: ['course_activity_lecture'],
            submissionValue: ['course_activity_lecture'],
            submissionValueType: 'OBJECT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae6b',
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'field',
            extId: 'res.restext',
            value: 'Test2',
            submissionValue: ['Test2'],
            submissionValueType: 'FREE_TEXT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae63',
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
          {
            type: 'field',
            extId: 'res.comment',
            value: '',
            submissionValue: [''],
            submissionValueType: 'FREE_TEXT',
            valueMode: 'FROM_SUBMISSION',
            sectionId: '601048afea0edb00206dae62',
            elementId: '601048afea0edb00206dae65',
            eventId: '9a797766-8a48-40e4-ad0b-c28b516f32ff',
            rowIdx: null,
          },
        ],
        sequenceIdx: 1,
      },
    ],
  } as { [id: number]: TActivity[] };

  beforeEach(() =>
    renderWithState(
      <JointTeachingGroupMerger
        formId='test'
        activities={Object.values(activities).flat()}
      />,
    ),
  );

  it('renders without throwing', () => {
    renderWithState(
      <JointTeachingGroupMerger
        formId='test'
        activities={Object.values(activities).flat()}
      />,
      {
        initialState: { activities: { formIdTest: { submissionIdTest: [] } } },
      },
    );
  });

  it('renders Create joint teaching group header', () => {
    screen
      .getAllByText('Create joint teaching group')
      .forEach((element) => expect(element).toBeInTheDocument());
  });

  it.skip('renders disabled create button', () => {
    const createButton = screen.getByText('Create').closest('button');

    expect(createButton).toBeInTheDocument();
    expect(createButton?.disabled).toBeTruthy();
  });

  it('accepts activities as prop', () => {
    renderWithState(
      <JointTeachingGroupMerger
        formId='test'
        activities={Object.values(activities).flat()}
      />,
    );
  });
});
