export const FETCH_ACTIVITY_FILTER_LOOKUP_MAP =
  'filterLookupMap/FETCH_ACTIVITY_FILTER_LOOKUP_MAP';
export const FETCH_ACTIVITY_FILTER_LOOKUP_MAP_REQUEST =
  'filterLookupMap/FETCH_ACTIVITY_FILTER_LOOKUP_MAP_REQUEST';
export const FETCH_ACTIVITY_FILTER_LOOKUP_MAP_SUCCESS =
  'filterLookupMap/FETCH_ACTIVITY_FILTER_LOOKUP_MAP_SUCCESS';
export const FETCH_ACTIVITY_FILTER_LOOKUP_MAP_FAILURE =
  'filterLookupMap/FETCH_ACTIVITY_FILTER_LOOKUP_MAP_FAILURE';
