export const FETCH_ACTIVITY_TAGS_REQUEST = 'FETCH_ACTIVITY_TAGS_REQUEST';
export const FETCH_ACTIVITY_TAGS_SUCCESS = 'FETCH_ACTIVITY_TAGS_SUCCESS';
export const FETCH_ACTIVITY_TAGS_FAILURE = 'FETCH_ACTIVITY_TAGS_FAILURE';

export const CREATE_ACTIVITY_TAG_REQUEST = 'CREATE_ACTIVITY_TAG_REQUEST';
export const CREATE_ACTIVITY_TAG_SUCCESS = 'CREATE_ACTIVITY_TAG_SUCCESS';
export const CREATE_ACTIVITY_TAG_FAILURE = 'CREATE_ACTIVITY_TAG_FAILURE';

export const UPDATE_ACTIVITY_TAG_REQUEST = 'UPDATE_ACTIVITY_TAG_REQUEST';
export const UPDATE_ACTIVITY_TAG_SUCCESS = 'UPDATE_ACTIVITY_TAG_SUCCESS';
export const UPDATE_ACTIVITY_TAG_FAILURE = 'UPDATE_ACTIVITY_TAG_FAILURE';

export const DELETE_ACTIVITY_TAG_REQUEST = 'DELETE_ACTIVITY_TAG_REQUEST';
export const DELETE_ACTIVITY_TAG_SUCCESS = 'DELETE_ACTIVITY_TAG_SUCCESS';
export const DELETE_ACTIVITY_TAG_FAILURE = 'DELETE_ACTIVITY_TAG_FAILURE';

export const ASSIGN_ACTIVITIES_TO_TAG_REQUEST =
  'ASSIGN_ACTIVITIES_TO_TAG_REQUEST';
export const ASSIGN_ACTIVITIES_TO_TAG_SUCCESS =
  'ASSIGN_ACTIVITIES_TO_TAG_SUCCESS';
export const ASSIGN_ACTIVITIES_TO_TAG_FAILURE =
  'ASSIGN_ACTIVITIES_TO_TAG_FAILURE';
