export enum EFormDetailTabs {
  FORM_INFO = 'FORM_INFO',
  SUBMISSIONS = 'SUBMISSIONS',
  ACTIVITIES = 'ACTIVITIES',
  ACTIVITY_DESIGNER = 'ACTIVITY_DESIGNER',
  CONSTRAINT_MANAGER = 'CONSTRAINT_MANAGER',
};
