export enum EFormDetailTabs {
  SUBMISSIONS = 'SUBMISSIONS',
  JOINT_TEACHING = 'JOINT_TEACHING',
  GROUP_MANAGEMENT = 'GROUP_MANAGEMENT',
  ACTIVITIES = 'ACTIVITIES',
  ACTIVITY_DESIGNER = 'ACTIVITY_DESIGNER',
  CONSTRAINT_MANAGER = 'CONSTRAINT_MANAGER',
}
