export const FETCH_ACTIVITIES_FOR_FORM = 'FETCH_ACTIVITIES_FOR_FORM';
export const FETCH_ACTIVITIES_FOR_FORM_REQUEST =
  'FETCH_ACTIVITIES_FOR_FORM_REQUEST';
export const FETCH_ACTIVITIES_FOR_FORM_SUCCESS =
  'FETCH_ACTIVITIES_FOR_FORM_SUCCESS';
export const FETCH_ACTIVITIES_FOR_FORM_FAILURE =
  'FETCH_ACTIVITIES_FOR_FORM_FAILURE';

export const FETCH_ALL_ACTIVITIES_FOR_FORM = 'FETCH_ALL_ACTIVITIES_FOR_FORM';
export const FETCH_ALL_ACTIVITIES_FOR_FORM_REQUEST =
  'FETCH_ALL_ACTIVITIES_FOR_FORM_REQUEST';
export const FETCH_ALL_ACTIVITIES_FOR_FORM_SUCCESS =
  'FETCH_ALL_ACTIVITIES_FOR_FORM_SUCCESS';
export const FETCH_ALL_ACTIVITIES_FOR_FORM_FAILURE =
  'FETCH_ALL_ACTIVITIES_FOR_FORM_FAILURE';

export const RESET_ALL_ACTIVITIES = 'RESET_ALL_ACTIVITIES';

export const FETCH_ACTIVITIES_FOR_FORM_INSTANCE_REQUEST =
  'FETCH_ACTIVITIES_FOR_FORM_INSTANCE_REQUEST';
export const FETCH_ACTIVITIES_FOR_FORM_INSTANCE_SUCCESS =
  'FETCH_ACTIVITIES_FOR_FORM_INSTANCE_SUCCESS';
export const FETCH_ACTIVITIES_FOR_FORM_INSTANCE_FAILURE =
  'FETCH_ACTIVITIES_FOR_FORM_INSTANCE_FAILURE';

export const SAVE_ACTIVITIES_FOR_FORM_INSTANCE_REQUEST =
  'SAVE_ACTIVITIES_FOR_FORM_INSTANCE_REQUEST';
export const SAVE_ACTIVITIES_FOR_FORM_INSTANCE_SUCCESS =
  'SAVE_ACTIVITIES_FOR_FORM_INSTANCE_SUCCESS';
export const SAVE_ACTIVITIES_FOR_FORM_INSTANCE_FAILURE =
  'SAVE_ACTIVITIES_FOR_FORM_INSTANCE_FAILURE';

export const DELETE_ACTIVITIES_FOR_FORM_REQUEST =
  'DELETE_ACTIVITIES_FOR_FORM_REQUEST';
export const DELETE_ACTIVITIES_FOR_FORM_SUCCESS =
  'DELETE_ACTIVITIES_FOR_FORM_SUCCESS';
export const DELETE_ACTIVITIES_FOR_FORM_FAILURE =
  'DELETE_ACTIVITIES_FOR_FORM_FAILURE';

export const UPDATE_ACTIVITY_REQUEST = 'UPDATE_ACTIVITY_REQUEST';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
export const UPDATE_ACTIVITY_FAILURE = 'UPDATE_ACTIVITY_FAILURE';

export const UPDATE_ACTIVITIES_REQUEST = 'UPDATE_ACTIVITIES_REQUEST';
export const UPDATE_ACTIVITIES_SUCCESS = 'UPDATE_ACTIVITIES_SUCCESS';
export const UPDATE_ACTIVITIES_FAILURE = 'UPDATE_ACTIVITIES_FAILURE';

export const SET_SCHEDULING_STATUS_OF_ACTIVITIES_REQUEST =
  'SET_SCHEDULING_STATUS_OF_ACTIVITIES_REQUEST';
export const SET_SCHEDULING_STATUS_OF_ACTIVITIES_SUCCESS =
  'SET_SCHEDULING_STATUS_OF_ACTIVITIES_SUCCESS';
export const SET_SCHEDULING_STATUS_OF_ACTIVITIES_FAILURE =
  'SET_SCHEDULING_STATUS_OF_ACTIVITIES_FAILURE';

export const REORDER_ACTIVITIES_REQUEST = 'REORDER_ACTIVITIES_REQUEST';
export const REORDER_ACTIVITIES_SUCCESS = 'REORDER_ACTIVITIES_SUCCESS';
export const REORDER_ACTIVITIES_FAILURE = 'REORDER_ACTIVITIES_FAILURE';

export const SCHEDULE_ACTIVITIES_REQUEST = 'SCHEDULE_ACTIVITIES_REQUEST';
export const SCHEDULE_ACTIVITIES_SUCCESS = 'SCHEDULE_ACTIVITIES_SUCCESS';
export const SCHEDULE_ACTIVITIES_FAILURE = 'SCHEDULE_ACTIVITIES_FAILURE';

export const MANUALLY_OVERRIDE_ACTIVITY_VALUE_REQUEST =
  'MANUALLY_OVERRIDE_ACTIVITY_VALUE_REQUEST';
export const MANUALLY_OVERRIDE_ACTIVITY_VALUE_SUCCESS =
  'MANUALLY_OVERRIDE_ACTIVITY_VALUE_SUCCESS';
export const MANUALLY_OVERRIDE_ACTIVITY_VALUE_FAILURE =
  'MANUALLY_OVERRIDE_ACTIVITY_VALUE_FAILURE';

export const REVERT_TO_SUBMISSION_VALUE_REQUEST =
  'REVERT_TO_SUBMISSION_VALUE_REQUEST';
export const REVERT_TO_SUBMISSION_VALUE_SUCCESS =
  'REVERT_TO_SUBMISSION_VALUE_SUCCESS';
export const REVERT_TO_SUBMISSION_VALUE_FAILURE =
  'REVERT_TO_SUBMISSION_VALUE_FAILURE';

export const DELETE_ACTIVITIES_FOR_FORM_INSTANCE_REQUEST =
  'DELETE_ACTIVITIES_FOR_FORM_INSTANCE_REQUEST';
export const DELETE_ACTIVITIES_FOR_FORM_INSTANCE_SUCCESS =
  'DELETE_ACTIVITIES_FOR_FORM_INSTANCE_SUCCESS';
export const DELETE_ACTIVITIES_FOR_FORM_INSTANCE_FAILURE =
  'DELETE_ACTIVITIES_FOR_FORM_INSTANCE_FAILURE';

export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS';
export const CREATE_ACTIVITY_REQUEST = 'CREATE_ACTIVITY_REQUEST';
export const CREATE_ACTIVITY_FAILURE = 'CREATE_ACTIVITY_FAILURE';

export const SET_UNMATCHED_ACTIVITIES = 'SET_UNMATCHED_ACTIVITIES';

export const GET_SELECTED_ACTIVITIES_SUCCESS = 'CREATE_ACTIVITY_SUCCESS';
export const GET_SELECTED_ACTIVITIES_REQUEST = 'CREATE_ACTIVITY_REQUEST';
export const GET_SELECTED_ACTIVITIES_FAILURE = 'CREATE_ACTIVITY_FAILURE';

export const UPDATE_ACTIVITY_IN_WORKER_PROGRESS =
  'UPDATE_ACTIVITY_IN_WORKER_PROGRESS';

export const GET_ACTIVITIES_IN_WORKER_PROGRESS_SUCCESS =
  'GET_ACTIVITIES_IN_WORKER_PROGRESS_SUCCESS';
export const GET_ACTIVITIES_IN_WORKER_PROGRESS_REQUEST =
  'GET_ACTIVITIES_IN_WORKER_PROGRESS_REQUEST';
export const GET_ACTIVITIES_IN_WORKER_PROGRESS_FAILURE =
  'GET_ACTIVITIES_IN_WORKER_PROGRESS_FAILURE';

export const RESET_ACTIVITY_ON_CANCEL_RESERVATION_BY_FORMINSTANCE_ID =
  'RESET_ACTIVITY_ON_CANCEL_RESERVATION_BY_FORMINSTANCE_ID';
