export const FETCH_ACTIVITY_GROUPS_REQUEST = 'FETCH_ACTIVITY_GROUPS_REQUEST';
export const FETCH_ACTIVITY_GROUPS_SUCCESS = 'FETCH_ACTIVITY_GROUPS_SUCCESS';
export const FETCH_ACTIVITY_GROUPS_FAILURE = 'FETCH_ACTIVITY_GROUPS_FAILURE';
