export const FETCH_ACTIVITY_GROUPS_REQUEST = 'FETCH_ACTIVITY_GROUPS_REQUEST';
export const FETCH_ACTIVITY_GROUPS_SUCCESS = 'FETCH_ACTIVITY_GROUPS_SUCCESS';
export const FETCH_ACTIVITY_GROUPS_FAILURE = 'FETCH_ACTIVITY_GROUPS_FAILURE';

export const CREATE_ACTIVITY_GROUP_REQUEST = 'CREATE_ACTIVITY_GROUP_REQUEST';
export const CREATE_ACTIVITY_GROUP_SUCCESS = 'CREATE_ACTIVITY_GROUP_SUCCESS';
export const CREATE_ACTIVITY_GROUP_FAILURE = 'CREATE_ACTIVITY_GROUP_FAILURE';

export const UPDATE_ACTIVITY_GROUP_REQUEST = 'UPDATE_ACTIVITY_GROUP_REQUEST';
export const UPDATE_ACTIVITY_GROUP_SUCCESS = 'UPDATE_ACTIVITY_GROUP_SUCCESS';
export const UPDATE_ACTIVITY_GROUP_FAILURE = 'UPDATE_ACTIVITY_GROUP_FAILURE';

export const DELETE_ACTIVITY_GROUP_REQUEST = 'DELETE_ACTIVITY_GROUP_REQUEST';
export const DELETE_ACTIVITY_GROUP_SUCCESS = 'DELETE_ACTIVITY_GROUP_SUCCESS';
export const DELETE_ACTIVITY_GROUP_FAILURE = 'DELETE_ACTIVITY_GROUP_FAILURE';

export const ASSIGN_ACTIVITIES_TO_GROUP_REQUEST =
  'ASSIGN_ACTIVITIES_TO_GROUP_REQUEST';
export const ASSIGN_ACTIVITIES_TO_GROUP_SUCCESS =
  'ASSIGN_ACTIVITIES_TO_GROUP_SUCCESS';
export const ASSIGN_ACTIVITIES_TO_GROUP_FAILURE =
  'ASSIGN_ACTIVITIES_TO_GROUP_FAILURE';
