#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
branch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} | sed s/.*[/]//)

echo Linting and prettying modified files. Diffing with $branch
yarn lint:diff $branch
yarn prettier:diff $branch
yarn test
