export const LOAD_FILTER = 'LOAD_FILTER';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const SET_FILTER = 'SET_FILTER';

export const SET_ACITIVTY_FILTER_OPTIONS = 'SET_ACITIVTY_FILTER_OPTIONS';
export const SET_ACTIVITY_FIlTER_MODE = 'SET_ACTIVITY_FIlTER_MODE';
export const SET_ACTIVITY_FILTER_INCLUSION = 'SET_ACTIVITY_FILTER_INCLUSION';