export const LOAD_FILTER = 'LOAD_FILTER';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const SET_FILTER = 'SET_FILTER';

export const SET_ACTIVITY_FILTER_OPTIONS = 'SET_ACITIVTY_FILTER_OPTIONS'; // DEPRECATED

export const SET_ACTIVITY_FILTER = 'SET_ACTIVITY_FILTER';
export const SET_ACTIVITY_FILTER_MODE = 'SET_ACTIVITY_FIlTER_MODE';
export const SET_ACTIVITY_FILTER_INCLUSION = 'SET_ACTIVITY_FILTER_INCLUSION';

export const SET_FORM_LOOKUPMAP = 'SET_FORM_LOOKUPMAP';
export const SET_SELECTED_FILTER_VALUES = 'SET_SELECTED_FILTER_VALUES';
