export const LOAD_FILTER = 'LOAD_FILTER';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const SET_FILTER = 'SET_FILTER';

export const SET_ACTIVITY_FILTER_OPTIONS = 'SET_ACITIVTY_FILTER_OPTIONS'; // DEPRECATED

export const SET_ACTIVITY_FILTER = 'SET_ACTIVITY_FILTER';
export const SET_ACTIVITY_FILTER_MODE = 'SET_ACTIVITY_FIlTER_MODE';
export const SET_ACTIVITY_FILTER_INCLUSION = 'SET_ACTIVITY_FILTER_INCLUSION';

export const SET_SELECTED_FILTER_VALUES = 'SET_SELECTED_FILTER_VALUES';

export const FETCH_FORM_LOOKUPMAP_REQUEST = 'FETCH_FORM_LOOKUPMAP_REQUEST';
export const FETCH_FORM_LOOKUPMAP_SUCCESS = 'FETCH_FORM_LOOKUPMAP_SUCCESS';
export const FETCH_FORM_LOOKUPMAP_FAILURE = 'FETCH_FORM_LOOKUPMAP_FAILURE';

export const LOAD_SELECTED_FILTER_VALUES_REQUEST =
  'LOAD_SELECTED_FILTER_VALUES_REQUEST';
export const LOAD_SELECTED_FILTER_VALUES_SUCCESS =
  'LOAD_SELECTED_FILTER_VALUES_SUCCESS';
export const LOAD_SELECTED_FILTER_VALUES_FAILURE =
  'LOAD_SELECTED_FILTER_VALUES_FAILURE';
